FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY src ./src

ARG NODE_ENV=production
ARG PORT=5000
ARG RAPID_API_KEY
ARG RAPID_API_HOST
ARG CORS_ORIGIN

ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV RAPID_API_KEY=$RAPID_API_KEY
ENV RAPID_API_HOST=$RAPID_API_HOST
ENV CORS_ORIGIN=$CORS_ORIGIN

EXPOSE 5000

CMD ["node", "src/app.js"]
